
server.port: 8080

app:
  login:
    username: admin
    password: admin
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ

swagger:
  project-title: "Cloud-Parking API"
  project-version: "v1"
  project-description: ""

spring:
  datasource:
    url: jdbc:postgresql://parking-db:5432/parking?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: admin
    password: admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace